#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["raisecontext-client @ git+https://github.com/pocketcontext/raisecontext.git@79c3a49deecbee45d1a202402d99687feb552252"]
# ///
from raisecontext_client.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
